prometheus:
  kube-state-metrics:
    releaseLabel: true
    metricLabelsAllowlist:
      - endpoints=[*]
      - jobs=[*]
      - namespaces=[*]
      - nodes=[*]
      - pods=[*]
      - services=[*]
    metricAnnotationsAllowList:
      - endpoints=[*]
      - jobs=[*]
      - namespaces=[*]
      - nodes=[*]
      - pods=[*]
      - services=[*]

  serviceAccounts:
    alertmanager:
      create: false

  kubeStateMetrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true
    hostNetwork: false

  prometheus-pushgateway:
    enabled: true
    persistentVolume:
      enabled: false

  alertmanager:
    enabled: false

  server:
    enabled: true
    remote_write:
    # CloudCoSe target skeleton. Target also includes tls and auth settings, extra headers and so on
    - url: https://app.cloudcose.com/storage/api/v2/write
      name: cloudcose

    # CloudCoSe Kubernetes data source id
    dataSourceId: null
    # Username which is used on CloudCoSe Kubernetes data source registration
    username: null
    # Password which is used on CloudCoSe Kubernetes data source registration
    password: null
    # Remote write CloudCoSe target tls CA certificate file
    caFile:

    configMapOverrideName: ""
    persistentVolume:
      enabled: false
    defaultFlagsOverride:
    - --enable-feature=agent
    - --config.file=/etc/config/prometheus.yml
    - --web.enable-lifecycle
    extraConfigmapMounts:
    # Config map with CA cert file
    - name: cert-config
      mountPath: /etc/cloudcose/ssl
      configMap: prometheus-server-cert-config
      subPath: ""
      readOnly: true
    extraSecretMounts:
    # Secret with password file
    - name: password-secret
      mountPath: /etc/cloudcose/auth
      subPath: ""
      secretName: prometheus-server-password-secret
      readOnly: true
  serverFiles:
    prometheus.yml:
      rule_files: []
